version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test_db"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]


  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    container_name: postgres-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgresadmin!"
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - "16543:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    logging:
      driver: none

volumes:
  node_modules_cache:
  db:
    driver: local
  pgadmin:
    driver: local

